# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "runjtu"
repo_name: "vpr-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 20

publish_readme: True
publish_gitpage: False
publish_wechat: False #

# file paths
json_readme_path: './docs/vpr-arxiv-daily.json'

md_readme_path: 'README.md'


# keywords to search
# topics: task/technique/dataset...
keywords:
   "Spatial AI": 
        filters: [ 
                  "Vision Language Navigation",  
                  "Large Scale NeRF", 
                  "Scene Understanding",
                  "Geo Localization"]
    "Localization and Mapping": 
        filters: ["GS SLAM", "CSLAM", "Crowd-Sourced Mapping", "Loop Closure Detection", "Re-Localization", "LiDAR Place Recognition", "Range Sensor Recognition", "Structure from Motion", "Visual Place Recognition", 
                  "VLAD","image retrieval"]

